# Task 1: Python Proficiency Check – AI Bootcamp Prep

## Section 1: Basics & Control Flow

### **Task 1**: FizzBuzz with a Twist

*Instruction*: Write a function that prints numbers from 1 to 50. For multiples of 3, print "AI", for multiples of 5 print "Bootcamp", and for multiples of both 3 and 5 print "AI Bootcamp".

In [ ]:
def fizzbuzz_ai_bootcamp():
  for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
      print("AI Bootcamp")
    elif i % 3 == 0:
      print("AI")
    elif i % 5 == 0:
      print("Bootcamp")
    else:
      print(i)
fizzbuzz_ai_bootcamp()



1
2
AI
4
Bootcamp
AI
7
8
AI
Bootcamp
11
AI
13
14
AI Bootcamp
16
17
AI
19
Bootcamp
AI
22
23
AI
Bootcamp
26
AI
28
29
AI Bootcamp
31
32
AI
34
Bootcamp
AI
37
38
AI
Bootcamp
41
AI
43
44
AI Bootcamp
46
47
AI
49
Bootcamp


### **Task 2**: List Comprehensions and Functions

*Instruction*: Given a list of numbers, square only the even numbers using a list comprehension and define a function that returns the result.

In [3]:
def square_evens(numbers):
    even_numbers = [num for num in numbers if num % 2 == 0]
    squared_evens = [num ** 2 for num in even_numbers]
    return squared_evens

print(square_evens([1, 2, 3, 4, 5, 6]))

[4, 16, 36]


## Section 2: Data Structures & File I/O

### **Task 3**: Word Frequency from a File

*Instruction*: Read the provided text file (Sample_For_Task1.txt) and return the 5 most common words (ignoring punctuation and case).

In [ ]:
from collections import Counter
import re

def top_5_words(filepath):
    try:
        with open(filepath, 'r') as file:
            text = file.read().lower()  # Read and convert to lowercase
            words = re.findall(r'\b\w+\b', text)  # Find all words
            word_counts = Counter(words)  # Count word frequencies
            return word_counts.most_common(5)  # Return top 5
    except FileNotFoundError:
        print(f"Error: File '{filepath}' not found.")
        return []  # Return empty list in case of error

top_5_words('/Sample_For_Task1 (1).txt')


[('the', 5), ('quick', 2), ('fox', 2), ('dog', 2), ('and', 2)]

## Section 3: NumPy & pandas

### **Task 4**: NumPy Matrix Magic

*Instruction*: Create a 5x5 matrix with random integers from 1 to 10. Replace all elements greater than 5 with 0.

In [ ]:
import numpy as np

def matrix_transform():
    matrix = np.random.randint(1, 11, size=(5, 5))

    matrix[matrix > 5] = 0

    print(matrix)

matrix_transform()

[[5 0 5 0 0]
 [1 1 0 0 0]
 [0 0 1 5 1]
 [1 4 0 1 0]
 [0 0 1 0 4]]


### **Task 5**: pandas DataFrame Manipulation

*Instruction*: Given the following dictionary, convert it into a DataFrame, calculate the average score per student, and add it as a new column.

In [2]:
import pandas as pd

data = {'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Math': [85, 72, 90, 78, 88],
        'Science': [92, 85, 76, 80, 95],
        'English': [78, 82, 88, 90, 85]}

df = pd.DataFrame(data)
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1)
print(df)



   Student  Math  Science  English    Average
0    Alice    85       92       78  85.000000
1      Bob    72       85       82  79.666667
2  Charlie    90       76       88  84.666667
3    David    78       80       90  82.666667
4      Eve    88       95       85  89.333333


## Section 4: Visualization & Logic

### **Task 6**: Simple Data Visualization

*Instruction*: Use matplotlib to create a bar chart showing the average score per subject from the DataFrame in the previous task.

In [4]:
import matplotlib.pyplot as plt

plt.bar(['Math', 'Science', 'English'], df[['Math', 'Science', 'English']].mean())
plt.xlabel('Subject')
plt.ylabel('Average Score')
plt.title('Average Scores per Subject')
plt.show()


## Section 5: Mini-Project Challenge

### **Task 7**: Build a Mini Calculator with Exception Handling

*Instruction*: Write a function that takes two numbers and an operator as input (+, -, *, /). Return the result, and handle divide-by-zero and invalid operator cases with appropriate error messages.

In [5]:
def calculator(a, b, operator):
    try:
        if operator == '+':
            return a + b
        elif operator == '-':
            return a - b
        elif operator == '*':
            return a * b
        elif operator == '/':
            if b == 0:
                raise ZeroDivisionError
                return a / b
        else:
            raise ValueError
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")
        return None
    except ValueError:
        print("Error: Invalid operator. Please use +, -, *, or /.")
        return None
calculator(10, 8, '+')

18